import type { Metadata } from 'next'
import './globals.css'
import SideNav from '../components/layout/sidenav'
import { outfit } from '@/components/ui/fonts'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${outfit.className} antialiased flex h-screen flex-col md:flex-row md:overflow-hidden bg-black text-gray-50`}
			>
				<div className='w-full flex-none md:w-64'>
					<SideNav />
				</div>
				<div className='md:flex flex-grow justify-center md:p-10'>
					{children}
				</div>
			</body>
		</html>
	)
}
